name: Run Python Script
on: 
  workflow_dispatch:
  
env:
 message_id: ${{ secrets.MESSAGE_ID }}
 
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/checkout@v4
        with:
          Python-version: '3.10'

      - name: Run Python Scripts
        run: |
           python -m pip install requests     
           python main.py
        
     
        

      
