name: Run Python Script with Secrets and Inputs

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'Provide a workflow input'
        required: true
# env can be outside of the body too 
# env:
#     API_KEY: ${{ secrets.API_KEY }}
#     SECRET_KEY: ${{ secrets.SECRET_KEY }}
#     INPUT_USER_INPUT: ${{ github.event.inputs.user_input }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # pre-package code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Python script
        run: 
            python main.py
            # python src/main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          INPUT_USER_INPUT: ${{ github.event.inputs.user_input }}
        
